// Created by Crowbar 0.71

$modelname "ps2models\v_WeaponAttachment_NS_Scope4x.mdl"

$bodygroup "scope"
{
	studio "WeaponAttachment_NS_Scope4x.smd"
}


$surfaceprop "default"

$contents "solid"

$illumposition 0 -1.795 1.118

$cdmaterials "models\ps2models\"

$cbox 0 0 0 0 0 0

$bbox -3.081 -1.119 -2.705 6.808 1.119 5.056

$hboxset "default"


$sequence "idle" {
	"anims\idle.smd"
	fps 30
    snap
}
